/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
import { type SerializeShadowRootOptions } from "@stencil/react-output-target/ssr";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export { MyComponent } from "./my-component.server.js";
export { SsbBadge } from "./ssb-badge.server.js";
export { SsbButton } from "./ssb-button.server.js";
