/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { MyComponent as MyComponentElement } from "@stencil-storybook-boilerplate/core/dist/components/my-component.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type MyComponentEvents = { onButtonClick: EventName<CustomEvent<any>> };

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    properties: {
        count: 'count',
        first: 'first',
        middle: 'middle',
        last: 'last',
        aria: 'aria'
    },
    hydrateModule: import('@stencil-storybook-boilerplate/core/hydrate'),
    serializeShadowRoot
});
