'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type MyComponentCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { MyComponent as MyComponentElement } from "@stencil-storybook-boilerplate/core/dist/components/my-component.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type MyComponentEvents = { onButtonClick: EventName<MyComponentCustomEvent<any>> };

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent, 'first'> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent, 'first'>({
    tagName: 'my-component',
    properties: {
        count: 'count',
        first: 'first',
        middle: 'middle',
        last: 'last',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComponent as StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent, 'first'>,
    serializeShadowRoot
});
