'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCard as SsbCardElement, defineCustomElement as defineSsbCard } from "@stencil-storybook-boilerplate/core/dist/components/ssb-card.js";

export type SsbCardEvents = NonNullable<unknown>;

export const SsbCard: StencilReactComponent<SsbCardElement, SsbCardEvents, Components.SsbCard> = /*@__PURE__*/ createComponent<SsbCardElement, SsbCardEvents, Components.SsbCard>({
    tagName: 'ssb-card',
    elementClass: SsbCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbCardEvents,
    defineCustomElement: defineSsbCard
});
