'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbPopoverCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbPopover as SsbPopoverElement, defineCustomElement as defineSsbPopover } from "@stencil-storybook-boilerplate/core/dist/components/ssb-popover.js";

export type SsbPopoverEvents = { onSsbOpenChange: EventName<SsbPopoverCustomEvent<{ open: boolean }>> };

export const SsbPopover: StencilReactComponent<SsbPopoverElement, SsbPopoverEvents, Components.SsbPopover> = /*@__PURE__*/ createComponent<SsbPopoverElement, SsbPopoverEvents, Components.SsbPopover>({
    tagName: 'ssb-popover',
    elementClass: SsbPopoverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbOpenChange: 'ssbOpenChange' } as SsbPopoverEvents,
    defineCustomElement: defineSsbPopover
});
