'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbComboboxCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCombobox as SsbComboboxElement, defineCustomElement as defineSsbCombobox } from "@stencil-storybook-boilerplate/core/dist/components/ssb-combobox.js";

export type SsbComboboxEvents = {
    onSsbChange: EventName<SsbComboboxCustomEvent<{ value: string }>>,
    onSsbOpenChange: EventName<SsbComboboxCustomEvent<{ open: boolean }>>
};

export const SsbCombobox: StencilReactComponent<SsbComboboxElement, SsbComboboxEvents, Components.SsbCombobox> = /*@__PURE__*/ createComponent<SsbComboboxElement, SsbComboboxEvents, Components.SsbCombobox>({
    tagName: 'ssb-combobox',
    elementClass: SsbComboboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbChange: 'ssbChange',
        onSsbOpenChange: 'ssbOpenChange'
    } as SsbComboboxEvents,
    defineCustomElement: defineSsbCombobox
});
