'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbEmpty as SsbEmptyElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-empty.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbEmptyEvents = NonNullable<unknown>;

export const SsbEmpty: StencilReactComponent<SsbEmptyElement, SsbEmptyEvents, Components.SsbEmpty> = /*@__PURE__*/ createComponent<SsbEmptyElement, SsbEmptyEvents, Components.SsbEmpty>({
    tagName: 'ssb-empty',
    properties: { aria: 'aria' },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbEmpty as StencilReactComponent<SsbEmptyElement, SsbEmptyEvents, Components.SsbEmpty>,
    serializeShadowRoot
});
