'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbScrollArea as SsbScrollAreaElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-scroll-area.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbScrollAreaEvents = NonNullable<unknown>;

export const SsbScrollArea: StencilReactComponent<SsbScrollAreaElement, SsbScrollAreaEvents, Components.SsbScrollArea> = /*@__PURE__*/ createComponent<SsbScrollAreaElement, SsbScrollAreaEvents, Components.SsbScrollArea>({
    tagName: 'ssb-scroll-area',
    properties: {
        maxHeight: 'max-height',
        orientation: 'orientation',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbScrollArea as StencilReactComponent<SsbScrollAreaElement, SsbScrollAreaEvents, Components.SsbScrollArea>,
    serializeShadowRoot
});
