'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbSwitchCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSwitch as SsbSwitchElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-switch.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbSwitchEvents = { onSsbChange: EventName<SsbSwitchCustomEvent<{ checked: boolean }>> };

export const SsbSwitch: StencilReactComponent<SsbSwitchElement, SsbSwitchEvents, Components.SsbSwitch> = /*@__PURE__*/ createComponent<SsbSwitchElement, SsbSwitchEvents, Components.SsbSwitch>({
    tagName: 'ssb-switch',
    properties: {
        checked: 'checked',
        disabled: 'disabled',
        name: 'name',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbSwitch as StencilReactComponent<SsbSwitchElement, SsbSwitchEvents, Components.SsbSwitch>,
    serializeShadowRoot
});
