'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type PaginationPageChangeDetail, type SsbPaginationCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbPagination as SsbPaginationElement, defineCustomElement as defineSsbPagination } from "@stencil-storybook-boilerplate/core/dist/components/ssb-pagination.js";

export type SsbPaginationEvents = { onSsbPageChange: EventName<SsbPaginationCustomEvent<PaginationPageChangeDetail>> };

export const SsbPagination: StencilReactComponent<SsbPaginationElement, SsbPaginationEvents, Components.SsbPagination> = /*@__PURE__*/ createComponent<SsbPaginationElement, SsbPaginationEvents, Components.SsbPagination>({
    tagName: 'ssb-pagination',
    elementClass: SsbPaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbPageChange: 'ssbPageChange' } as SsbPaginationEvents,
    defineCustomElement: defineSsbPagination
});
