'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbBadge as SsbBadgeElement, defineCustomElement as defineSsbBadge } from "@stencil-storybook-boilerplate/core/dist/components/ssb-badge.js";

export type SsbBadgeEvents = NonNullable<unknown>;

export const SsbBadge: StencilReactComponent<SsbBadgeElement, SsbBadgeEvents, Components.SsbBadge> = /*@__PURE__*/ createComponent<SsbBadgeElement, SsbBadgeEvents, Components.SsbBadge>({
    tagName: 'ssb-badge',
    elementClass: SsbBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbBadgeEvents,
    defineCustomElement: defineSsbBadge
});
