'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbAlertDialogCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAlertDialog as SsbAlertDialogElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-alert-dialog.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbAlertDialogEvents = {
    onSsbConfirm: EventName<SsbAlertDialogCustomEvent<void>>,
    onSsbCancel: EventName<SsbAlertDialogCustomEvent<void>>,
    onSsbOpenChange: EventName<SsbAlertDialogCustomEvent<{ open: boolean }>>
};

export const SsbAlertDialog: StencilReactComponent<SsbAlertDialogElement, SsbAlertDialogEvents, Components.SsbAlertDialog> = /*@__PURE__*/ createComponent<SsbAlertDialogElement, SsbAlertDialogEvents, Components.SsbAlertDialog>({
    tagName: 'ssb-alert-dialog',
    properties: {
        open: 'open',
        dialogTitle: 'dialog-title',
        description: 'description',
        confirmLabel: 'confirm-label',
        cancelLabel: 'cancel-label',
        destructive: 'destructive',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbAlertDialog as StencilReactComponent<SsbAlertDialogElement, SsbAlertDialogEvents, Components.SsbAlertDialog>,
    serializeShadowRoot
});
