'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbButton as SsbButtonElement, defineCustomElement as defineSsbButton } from "@stencil-storybook-boilerplate/core/dist/components/ssb-button.js";

export type SsbButtonEvents = NonNullable<unknown>;

export const SsbButton: StencilReactComponent<SsbButtonElement, SsbButtonEvents, Components.SsbButton> = /*@__PURE__*/ createComponent<SsbButtonElement, SsbButtonEvents, Components.SsbButton>({
    tagName: 'ssb-button',
    elementClass: SsbButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbButtonEvents,
    defineCustomElement: defineSsbButton
});
