'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbDialogCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbDialog as SsbDialogElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-dialog.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbDialogEvents = { onSsbOpenChange: EventName<SsbDialogCustomEvent<{ open: boolean }>> };

export const SsbDialog: StencilReactComponent<SsbDialogElement, SsbDialogEvents, Components.SsbDialog> = /*@__PURE__*/ createComponent<SsbDialogElement, SsbDialogEvents, Components.SsbDialog>({
    tagName: 'ssb-dialog',
    properties: {
        open: 'open',
        dialogTitle: 'dialog-title',
        description: 'description',
        hideClose: 'hide-close',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbDialog as StencilReactComponent<SsbDialogElement, SsbDialogEvents, Components.SsbDialog>,
    serializeShadowRoot
});
