'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbButtonGroup as SsbButtonGroupElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-button-group.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbButtonGroupEvents = NonNullable<unknown>;

export const SsbButtonGroup: StencilReactComponent<SsbButtonGroupElement, SsbButtonGroupEvents, Components.SsbButtonGroup> = /*@__PURE__*/ createComponent<SsbButtonGroupElement, SsbButtonGroupEvents, Components.SsbButtonGroup>({
    tagName: 'ssb-button-group',
    properties: { aria: 'aria' },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbButtonGroup as StencilReactComponent<SsbButtonGroupElement, SsbButtonGroupEvents, Components.SsbButtonGroup>,
    serializeShadowRoot
});
