'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbBreadcrumb as SsbBreadcrumbElement, defineCustomElement as defineSsbBreadcrumb } from "@stencil-storybook-boilerplate/core/dist/components/ssb-breadcrumb.js";

export type SsbBreadcrumbEvents = NonNullable<unknown>;

export const SsbBreadcrumb: StencilReactComponent<SsbBreadcrumbElement, SsbBreadcrumbEvents, Components.SsbBreadcrumb> = /*@__PURE__*/ createComponent<SsbBreadcrumbElement, SsbBreadcrumbEvents, Components.SsbBreadcrumb>({
    tagName: 'ssb-breadcrumb',
    elementClass: SsbBreadcrumbElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbBreadcrumbEvents,
    defineCustomElement: defineSsbBreadcrumb
});
