'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSkeleton as SsbSkeletonElement, defineCustomElement as defineSsbSkeleton } from "@stencil-storybook-boilerplate/core/dist/components/ssb-skeleton.js";

export type SsbSkeletonEvents = NonNullable<unknown>;

export const SsbSkeleton: StencilReactComponent<SsbSkeletonElement, SsbSkeletonEvents, Components.SsbSkeleton> = /*@__PURE__*/ createComponent<SsbSkeletonElement, SsbSkeletonEvents, Components.SsbSkeleton>({
    tagName: 'ssb-skeleton',
    elementClass: SsbSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbSkeletonEvents,
    defineCustomElement: defineSsbSkeleton
});
