'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbTabsCustomEvent, type TabsChangeDetail } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTabs as SsbTabsElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-tabs.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbTabsEvents = { onSsbChange: EventName<SsbTabsCustomEvent<TabsChangeDetail>> };

export const SsbTabs: StencilReactComponent<SsbTabsElement, SsbTabsEvents, Components.SsbTabs> = /*@__PURE__*/ createComponent<SsbTabsElement, SsbTabsEvents, Components.SsbTabs>({
    tagName: 'ssb-tabs',
    properties: {
        tabs: 'tabs',
        value: 'value',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbTabs as StencilReactComponent<SsbTabsElement, SsbTabsEvents, Components.SsbTabs>,
    serializeShadowRoot
});
