'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbChart as SsbChartElement, defineCustomElement as defineSsbChart } from "@stencil-storybook-boilerplate/core/dist/components/ssb-chart.js";

export type SsbChartEvents = NonNullable<unknown>;

export const SsbChart: StencilReactComponent<SsbChartElement, SsbChartEvents, Components.SsbChart> = /*@__PURE__*/ createComponent<SsbChartElement, SsbChartEvents, Components.SsbChart>({
    tagName: 'ssb-chart',
    elementClass: SsbChartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbChartEvents,
    defineCustomElement: defineSsbChart
});
