'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAvatar as SsbAvatarElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-avatar.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbAvatarEvents = NonNullable<unknown>;

export const SsbAvatar: StencilReactComponent<SsbAvatarElement, SsbAvatarEvents, Components.SsbAvatar> = /*@__PURE__*/ createComponent<SsbAvatarElement, SsbAvatarEvents, Components.SsbAvatar>({
    tagName: 'ssb-avatar',
    properties: {
        src: 'src',
        alt: 'alt',
        initials: 'initials',
        shape: 'shape',
        size: 'size',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbAvatar as StencilReactComponent<SsbAvatarElement, SsbAvatarEvents, Components.SsbAvatar>,
    serializeShadowRoot
});
