'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAccordion as SsbAccordionElement, defineCustomElement as defineSsbAccordion } from "@stencil-storybook-boilerplate/core/dist/components/ssb-accordion.js";

export type SsbAccordionEvents = NonNullable<unknown>;

export const SsbAccordion: StencilReactComponent<SsbAccordionElement, SsbAccordionEvents, Components.SsbAccordion> = /*@__PURE__*/ createComponent<SsbAccordionElement, SsbAccordionEvents, Components.SsbAccordion>({
    tagName: 'ssb-accordion',
    elementClass: SsbAccordionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbAccordionEvents,
    defineCustomElement: defineSsbAccordion
});
