'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbProgress as SsbProgressElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-progress.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbProgressEvents = NonNullable<unknown>;

export const SsbProgress: StencilReactComponent<SsbProgressElement, SsbProgressEvents, Components.SsbProgress> = /*@__PURE__*/ createComponent<SsbProgressElement, SsbProgressEvents, Components.SsbProgress>({
    tagName: 'ssb-progress',
    properties: {
        value: 'value',
        max: 'max',
        label: 'label',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbProgress as StencilReactComponent<SsbProgressElement, SsbProgressEvents, Components.SsbProgress>,
    serializeShadowRoot
});
