'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbSliderCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSlider as SsbSliderElement, defineCustomElement as defineSsbSlider } from "@stencil-storybook-boilerplate/core/dist/components/ssb-slider.js";

export type SsbSliderEvents = {
    onSsbInput: EventName<SsbSliderCustomEvent<{ value: number }>>,
    onSsbChange: EventName<SsbSliderCustomEvent<{ value: number }>>
};

export const SsbSlider: StencilReactComponent<SsbSliderElement, SsbSliderEvents, Components.SsbSlider> = /*@__PURE__*/ createComponent<SsbSliderElement, SsbSliderEvents, Components.SsbSlider>({
    tagName: 'ssb-slider',
    elementClass: SsbSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbInput: 'ssbInput',
        onSsbChange: 'ssbChange'
    } as SsbSliderEvents,
    defineCustomElement: defineSsbSlider
});
