'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbInputGroup as SsbInputGroupElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-input-group.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbInputGroupEvents = NonNullable<unknown>;

export const SsbInputGroup: StencilReactComponent<SsbInputGroupElement, SsbInputGroupEvents, Components.SsbInputGroup> = /*@__PURE__*/ createComponent<SsbInputGroupElement, SsbInputGroupEvents, Components.SsbInputGroup>({
    tagName: 'ssb-input-group',
    properties: { aria: 'aria' },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbInputGroup as StencilReactComponent<SsbInputGroupElement, SsbInputGroupEvents, Components.SsbInputGroup>,
    serializeShadowRoot
});
