'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAlert as SsbAlertElement, defineCustomElement as defineSsbAlert } from "@stencil-storybook-boilerplate/core/dist/components/ssb-alert.js";

export type SsbAlertEvents = NonNullable<unknown>;

export const SsbAlert: StencilReactComponent<SsbAlertElement, SsbAlertEvents, Components.SsbAlert> = /*@__PURE__*/ createComponent<SsbAlertElement, SsbAlertEvents, Components.SsbAlert>({
    tagName: 'ssb-alert',
    elementClass: SsbAlertElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbAlertEvents,
    defineCustomElement: defineSsbAlert
});
