'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbSelectCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSelect as SsbSelectElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-select.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbSelectEvents = {
    onSsbChange: EventName<SsbSelectCustomEvent<{ value: string }>>,
    onSsbOpenChange: EventName<SsbSelectCustomEvent<{ open: boolean }>>
};

export const SsbSelect: StencilReactComponent<SsbSelectElement, SsbSelectEvents, Components.SsbSelect> = /*@__PURE__*/ createComponent<SsbSelectElement, SsbSelectEvents, Components.SsbSelect>({
    tagName: 'ssb-select',
    properties: {
        options: 'options',
        value: 'value',
        placeholder: 'placeholder',
        disabled: 'disabled',
        name: 'name',
        open: 'open',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbSelect as StencilReactComponent<SsbSelectElement, SsbSelectEvents, Components.SsbSelect>,
    serializeShadowRoot
});
