'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbInputCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbInput as SsbInputElement, defineCustomElement as defineSsbInput } from "@stencil-storybook-boilerplate/core/dist/components/ssb-input.js";

export type SsbInputEvents = {
    onSsbInput: EventName<SsbInputCustomEvent<{ value: string }>>,
    onSsbChange: EventName<SsbInputCustomEvent<{ value: string }>>
};

export const SsbInput: StencilReactComponent<SsbInputElement, SsbInputEvents, Components.SsbInput> = /*@__PURE__*/ createComponent<SsbInputElement, SsbInputEvents, Components.SsbInput>({
    tagName: 'ssb-input',
    elementClass: SsbInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbInput: 'ssbInput',
        onSsbChange: 'ssbChange'
    } as SsbInputEvents,
    defineCustomElement: defineSsbInput
});
