'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbCheckboxCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCheckbox as SsbCheckboxElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-checkbox.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbCheckboxEvents = { onSsbChange: EventName<SsbCheckboxCustomEvent<{ checked: boolean }>> };

export const SsbCheckbox: StencilReactComponent<SsbCheckboxElement, SsbCheckboxEvents, Components.SsbCheckbox> = /*@__PURE__*/ createComponent<SsbCheckboxElement, SsbCheckboxEvents, Components.SsbCheckbox>({
    tagName: 'ssb-checkbox',
    properties: {
        checked: 'checked',
        disabled: 'disabled',
        indeterminate: 'indeterminate',
        name: 'name',
        value: 'value',
        label: 'label',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbCheckbox as StencilReactComponent<SsbCheckboxElement, SsbCheckboxEvents, Components.SsbCheckbox>,
    serializeShadowRoot
});
