'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSpinner as SsbSpinnerElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-spinner.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbSpinnerEvents = NonNullable<unknown>;

export const SsbSpinner: StencilReactComponent<SsbSpinnerElement, SsbSpinnerEvents, Components.SsbSpinner> = /*@__PURE__*/ createComponent<SsbSpinnerElement, SsbSpinnerEvents, Components.SsbSpinner>({
    tagName: 'ssb-spinner',
    properties: {
        size: 'size',
        label: 'label',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbSpinner as StencilReactComponent<SsbSpinnerElement, SsbSpinnerEvents, Components.SsbSpinner>,
    serializeShadowRoot
});
