'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbField as SsbFieldElement, defineCustomElement as defineSsbField } from "@stencil-storybook-boilerplate/core/dist/components/ssb-field.js";

export type SsbFieldEvents = NonNullable<unknown>;

export const SsbField: StencilReactComponent<SsbFieldElement, SsbFieldEvents, Components.SsbField> = /*@__PURE__*/ createComponent<SsbFieldElement, SsbFieldEvents, Components.SsbField>({
    tagName: 'ssb-field',
    elementClass: SsbFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbFieldEvents,
    defineCustomElement: defineSsbField
});
