'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbKbd as SsbKbdElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-kbd.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbKbdEvents = NonNullable<unknown>;

export const SsbKbd: StencilReactComponent<SsbKbdElement, SsbKbdEvents, Components.SsbKbd> = /*@__PURE__*/ createComponent<SsbKbdElement, SsbKbdEvents, Components.SsbKbd>({
    tagName: 'ssb-kbd',
    properties: { aria: 'aria' },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbKbd as StencilReactComponent<SsbKbdElement, SsbKbdEvents, Components.SsbKbd>,
    serializeShadowRoot
});
