'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbButtonGroup as SsbButtonGroupElement, defineCustomElement as defineSsbButtonGroup } from "@stencil-storybook-boilerplate/core/dist/components/ssb-button-group.js";

export type SsbButtonGroupEvents = NonNullable<unknown>;

export const SsbButtonGroup: StencilReactComponent<SsbButtonGroupElement, SsbButtonGroupEvents, Components.SsbButtonGroup> = /*@__PURE__*/ createComponent<SsbButtonGroupElement, SsbButtonGroupEvents, Components.SsbButtonGroup>({
    tagName: 'ssb-button-group',
    elementClass: SsbButtonGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbButtonGroupEvents,
    defineCustomElement: defineSsbButtonGroup
});
