'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type AccordionItemToggleDetail, type SsbAccordionItemCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAccordionItem as SsbAccordionItemElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-accordion-item.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbAccordionItemEvents = { onSsbToggle: EventName<SsbAccordionItemCustomEvent<AccordionItemToggleDetail>> };

export const SsbAccordionItem: StencilReactComponent<SsbAccordionItemElement, SsbAccordionItemEvents, Components.SsbAccordionItem> = /*@__PURE__*/ createComponent<SsbAccordionItemElement, SsbAccordionItemEvents, Components.SsbAccordionItem>({
    tagName: 'ssb-accordion-item',
    properties: {
        heading: 'heading',
        open: 'open',
        disabled: 'disabled',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbAccordionItem as StencilReactComponent<SsbAccordionItemElement, SsbAccordionItemEvents, Components.SsbAccordionItem>,
    serializeShadowRoot
});
