'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbThemeSwitcherCustomEvent, type ThemeChangeDetail } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbThemeSwitcher as SsbThemeSwitcherElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-theme-switcher.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbThemeSwitcherEvents = { onSsbThemeChange: EventName<SsbThemeSwitcherCustomEvent<ThemeChangeDetail>> };

export const SsbThemeSwitcher: StencilReactComponent<SsbThemeSwitcherElement, SsbThemeSwitcherEvents, Components.SsbThemeSwitcher> = /*@__PURE__*/ createComponent<SsbThemeSwitcherElement, SsbThemeSwitcherEvents, Components.SsbThemeSwitcher>({
    tagName: 'ssb-theme-switcher',
    properties: {
        theme: 'theme',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbThemeSwitcher as StencilReactComponent<SsbThemeSwitcherElement, SsbThemeSwitcherEvents, Components.SsbThemeSwitcher>,
    serializeShadowRoot
});
