'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbDropdownMenuCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbDropdownMenu as SsbDropdownMenuElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-dropdown-menu.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbDropdownMenuEvents = {
    onSsbSelect: EventName<SsbDropdownMenuCustomEvent<{ value: string }>>,
    onSsbOpenChange: EventName<SsbDropdownMenuCustomEvent<{ open: boolean }>>
};

export const SsbDropdownMenu: StencilReactComponent<SsbDropdownMenuElement, SsbDropdownMenuEvents, Components.SsbDropdownMenu> = /*@__PURE__*/ createComponent<SsbDropdownMenuElement, SsbDropdownMenuEvents, Components.SsbDropdownMenu>({
    tagName: 'ssb-dropdown-menu',
    properties: {
        open: 'open',
        items: 'items',
        align: 'align',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbDropdownMenu as StencilReactComponent<SsbDropdownMenuElement, SsbDropdownMenuEvents, Components.SsbDropdownMenu>,
    serializeShadowRoot
});
