'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTooltip as SsbTooltipElement, defineCustomElement as defineSsbTooltip } from "@stencil-storybook-boilerplate/core/dist/components/ssb-tooltip.js";

export type SsbTooltipEvents = NonNullable<unknown>;

export const SsbTooltip: StencilReactComponent<SsbTooltipElement, SsbTooltipEvents, Components.SsbTooltip> = /*@__PURE__*/ createComponent<SsbTooltipElement, SsbTooltipEvents, Components.SsbTooltip>({
    tagName: 'ssb-tooltip',
    elementClass: SsbTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbTooltipEvents,
    defineCustomElement: defineSsbTooltip
});
