'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbScrollArea as SsbScrollAreaElement, defineCustomElement as defineSsbScrollArea } from "@stencil-storybook-boilerplate/core/dist/components/ssb-scroll-area.js";

export type SsbScrollAreaEvents = NonNullable<unknown>;

export const SsbScrollArea: StencilReactComponent<SsbScrollAreaElement, SsbScrollAreaEvents, Components.SsbScrollArea> = /*@__PURE__*/ createComponent<SsbScrollAreaElement, SsbScrollAreaEvents, Components.SsbScrollArea>({
    tagName: 'ssb-scroll-area',
    elementClass: SsbScrollAreaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbScrollAreaEvents,
    defineCustomElement: defineSsbScrollArea
});
