'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbItem as SsbItemElement, defineCustomElement as defineSsbItem } from "@stencil-storybook-boilerplate/core/dist/components/ssb-item.js";

export type SsbItemEvents = NonNullable<unknown>;

export const SsbItem: StencilReactComponent<SsbItemElement, SsbItemEvents, Components.SsbItem> = /*@__PURE__*/ createComponent<SsbItemElement, SsbItemEvents, Components.SsbItem>({
    tagName: 'ssb-item',
    elementClass: SsbItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbItemEvents,
    defineCustomElement: defineSsbItem
});
