'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbAlertDialogCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAlertDialog as SsbAlertDialogElement, defineCustomElement as defineSsbAlertDialog } from "@stencil-storybook-boilerplate/core/dist/components/ssb-alert-dialog.js";

export type SsbAlertDialogEvents = {
    onSsbConfirm: EventName<SsbAlertDialogCustomEvent<void>>,
    onSsbCancel: EventName<SsbAlertDialogCustomEvent<void>>,
    onSsbOpenChange: EventName<SsbAlertDialogCustomEvent<{ open: boolean }>>
};

export const SsbAlertDialog: StencilReactComponent<SsbAlertDialogElement, SsbAlertDialogEvents, Components.SsbAlertDialog> = /*@__PURE__*/ createComponent<SsbAlertDialogElement, SsbAlertDialogEvents, Components.SsbAlertDialog>({
    tagName: 'ssb-alert-dialog',
    elementClass: SsbAlertDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbConfirm: 'ssbConfirm',
        onSsbCancel: 'ssbCancel',
        onSsbOpenChange: 'ssbOpenChange'
    } as SsbAlertDialogEvents,
    defineCustomElement: defineSsbAlertDialog
});
