'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbSelectCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSelect as SsbSelectElement, defineCustomElement as defineSsbSelect } from "@stencil-storybook-boilerplate/core/dist/components/ssb-select.js";

export type SsbSelectEvents = {
    onSsbChange: EventName<SsbSelectCustomEvent<{ value: string }>>,
    onSsbOpenChange: EventName<SsbSelectCustomEvent<{ open: boolean }>>
};

export const SsbSelect: StencilReactComponent<SsbSelectElement, SsbSelectEvents, Components.SsbSelect> = /*@__PURE__*/ createComponent<SsbSelectElement, SsbSelectEvents, Components.SsbSelect>({
    tagName: 'ssb-select',
    elementClass: SsbSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbChange: 'ssbChange',
        onSsbOpenChange: 'ssbOpenChange'
    } as SsbSelectEvents,
    defineCustomElement: defineSsbSelect
});
