'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTable as SsbTableElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-table.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbTableEvents = NonNullable<unknown>;

export const SsbTable: StencilReactComponent<SsbTableElement, SsbTableEvents, Components.SsbTable> = /*@__PURE__*/ createComponent<SsbTableElement, SsbTableEvents, Components.SsbTable>({
    tagName: 'ssb-table',
    properties: {
        columns: 'columns',
        rows: 'rows',
        caption: 'caption',
        striped: 'striped',
        compact: 'compact',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbTable as StencilReactComponent<SsbTableElement, SsbTableEvents, Components.SsbTable>,
    serializeShadowRoot
});
