'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSkeleton as SsbSkeletonElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-skeleton.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbSkeletonEvents = NonNullable<unknown>;

export const SsbSkeleton: StencilReactComponent<SsbSkeletonElement, SsbSkeletonEvents, Components.SsbSkeleton> = /*@__PURE__*/ createComponent<SsbSkeletonElement, SsbSkeletonEvents, Components.SsbSkeleton>({
    tagName: 'ssb-skeleton',
    properties: {
        width: 'width',
        height: 'height',
        rounded: 'rounded',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbSkeleton as StencilReactComponent<SsbSkeletonElement, SsbSkeletonEvents, Components.SsbSkeleton>,
    serializeShadowRoot
});
