'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type AccordionItemToggleDetail, type SsbAccordionItemCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAccordionItem as SsbAccordionItemElement, defineCustomElement as defineSsbAccordionItem } from "@stencil-storybook-boilerplate/core/dist/components/ssb-accordion-item.js";

export type SsbAccordionItemEvents = { onSsbToggle: EventName<SsbAccordionItemCustomEvent<AccordionItemToggleDetail>> };

export const SsbAccordionItem: StencilReactComponent<SsbAccordionItemElement, SsbAccordionItemEvents, Components.SsbAccordionItem> = /*@__PURE__*/ createComponent<SsbAccordionItemElement, SsbAccordionItemEvents, Components.SsbAccordionItem>({
    tagName: 'ssb-accordion-item',
    elementClass: SsbAccordionItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbToggle: 'ssbToggle' } as SsbAccordionItemEvents,
    defineCustomElement: defineSsbAccordionItem
});
