'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbRadioCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbRadio as SsbRadioElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-radio.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbRadioEvents = { onSsbRadioSelect: EventName<SsbRadioCustomEvent<{ value: string }>> };

export const SsbRadio: StencilReactComponent<SsbRadioElement, SsbRadioEvents, Components.SsbRadio, 'value'> = /*@__PURE__*/ createComponent<SsbRadioElement, SsbRadioEvents, Components.SsbRadio, 'value'>({
    tagName: 'ssb-radio',
    properties: {
        value: 'value',
        checked: 'checked',
        disabled: 'disabled',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbRadio as StencilReactComponent<SsbRadioElement, SsbRadioEvents, Components.SsbRadio, 'value'>,
    serializeShadowRoot
});
