'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbDrawerCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbDrawer as SsbDrawerElement, defineCustomElement as defineSsbDrawer } from "@stencil-storybook-boilerplate/core/dist/components/ssb-drawer.js";

export type SsbDrawerEvents = { onSsbOpenChange: EventName<SsbDrawerCustomEvent<{ open: boolean }>> };

export const SsbDrawer: StencilReactComponent<SsbDrawerElement, SsbDrawerEvents, Components.SsbDrawer> = /*@__PURE__*/ createComponent<SsbDrawerElement, SsbDrawerEvents, Components.SsbDrawer>({
    tagName: 'ssb-drawer',
    elementClass: SsbDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbOpenChange: 'ssbOpenChange' } as SsbDrawerEvents,
    defineCustomElement: defineSsbDrawer
});
