'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbToastCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbToast as SsbToastElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-toast.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbToastEvents = { onSsbClose: EventName<SsbToastCustomEvent<void>> };

export const SsbToast: StencilReactComponent<SsbToastElement, SsbToastEvents, Components.SsbToast> = /*@__PURE__*/ createComponent<SsbToastElement, SsbToastEvents, Components.SsbToast>({
    tagName: 'ssb-toast',
    properties: {
        open: 'open',
        toastTitle: 'toast-title',
        description: 'description',
        variant: 'variant',
        duration: 'duration',
        dismissible: 'dismissible',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbToast as StencilReactComponent<SsbToastElement, SsbToastEvents, Components.SsbToast>,
    serializeShadowRoot
});
