'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbThemeSwitcherCustomEvent, type ThemeChangeDetail } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbThemeSwitcher as SsbThemeSwitcherElement, defineCustomElement as defineSsbThemeSwitcher } from "@stencil-storybook-boilerplate/core/dist/components/ssb-theme-switcher.js";

export type SsbThemeSwitcherEvents = { onSsbThemeChange: EventName<SsbThemeSwitcherCustomEvent<ThemeChangeDetail>> };

export const SsbThemeSwitcher: StencilReactComponent<SsbThemeSwitcherElement, SsbThemeSwitcherEvents, Components.SsbThemeSwitcher> = /*@__PURE__*/ createComponent<SsbThemeSwitcherElement, SsbThemeSwitcherEvents, Components.SsbThemeSwitcher>({
    tagName: 'ssb-theme-switcher',
    elementClass: SsbThemeSwitcherElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbThemeChange: 'ssbThemeChange' } as SsbThemeSwitcherEvents,
    defineCustomElement: defineSsbThemeSwitcher
});
