'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbSidebarCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSidebar as SsbSidebarElement, defineCustomElement as defineSsbSidebar } from "@stencil-storybook-boilerplate/core/dist/components/ssb-sidebar.js";

export type SsbSidebarEvents = { onSsbToggle: EventName<SsbSidebarCustomEvent<{ collapsed: boolean }>> };

export const SsbSidebar: StencilReactComponent<SsbSidebarElement, SsbSidebarEvents, Components.SsbSidebar> = /*@__PURE__*/ createComponent<SsbSidebarElement, SsbSidebarEvents, Components.SsbSidebar>({
    tagName: 'ssb-sidebar',
    elementClass: SsbSidebarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbToggle: 'ssbToggle' } as SsbSidebarEvents,
    defineCustomElement: defineSsbSidebar
});
