'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbField as SsbFieldElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-field.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbFieldEvents = NonNullable<unknown>;

export const SsbField: StencilReactComponent<SsbFieldElement, SsbFieldEvents, Components.SsbField> = /*@__PURE__*/ createComponent<SsbFieldElement, SsbFieldEvents, Components.SsbField>({
    tagName: 'ssb-field',
    properties: {
        label: 'label',
        description: 'description',
        error: 'error',
        required: 'required',
        fieldId: 'field-id',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbField as StencilReactComponent<SsbFieldElement, SsbFieldEvents, Components.SsbField>,
    serializeShadowRoot
});
