'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbRadioGroupCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbRadioGroup as SsbRadioGroupElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-radio-group.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbRadioGroupEvents = { onSsbChange: EventName<SsbRadioGroupCustomEvent<{ value: string }>> };

export const SsbRadioGroup: StencilReactComponent<SsbRadioGroupElement, SsbRadioGroupEvents, Components.SsbRadioGroup> = /*@__PURE__*/ createComponent<SsbRadioGroupElement, SsbRadioGroupEvents, Components.SsbRadioGroup>({
    tagName: 'ssb-radio-group',
    properties: {
        value: 'value',
        name: 'name',
        disabled: 'disabled',
        orientation: 'orientation',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbRadioGroup as StencilReactComponent<SsbRadioGroupElement, SsbRadioGroupEvents, Components.SsbRadioGroup>,
    serializeShadowRoot
});
