'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbRadioGroupCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbRadioGroup as SsbRadioGroupElement, defineCustomElement as defineSsbRadioGroup } from "@stencil-storybook-boilerplate/core/dist/components/ssb-radio-group.js";

export type SsbRadioGroupEvents = { onSsbChange: EventName<SsbRadioGroupCustomEvent<{ value: string }>> };

export const SsbRadioGroup: StencilReactComponent<SsbRadioGroupElement, SsbRadioGroupEvents, Components.SsbRadioGroup> = /*@__PURE__*/ createComponent<SsbRadioGroupElement, SsbRadioGroupEvents, Components.SsbRadioGroup>({
    tagName: 'ssb-radio-group',
    elementClass: SsbRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbChange: 'ssbChange' } as SsbRadioGroupEvents,
    defineCustomElement: defineSsbRadioGroup
});
