'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbDialogCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbDialog as SsbDialogElement, defineCustomElement as defineSsbDialog } from "@stencil-storybook-boilerplate/core/dist/components/ssb-dialog.js";

export type SsbDialogEvents = { onSsbOpenChange: EventName<SsbDialogCustomEvent<{ open: boolean }>> };

export const SsbDialog: StencilReactComponent<SsbDialogElement, SsbDialogEvents, Components.SsbDialog> = /*@__PURE__*/ createComponent<SsbDialogElement, SsbDialogEvents, Components.SsbDialog>({
    tagName: 'ssb-dialog',
    elementClass: SsbDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbOpenChange: 'ssbOpenChange' } as SsbDialogEvents,
    defineCustomElement: defineSsbDialog
});
