'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbPopoverCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbPopover as SsbPopoverElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-popover.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbPopoverEvents = { onSsbOpenChange: EventName<SsbPopoverCustomEvent<{ open: boolean }>> };

export const SsbPopover: StencilReactComponent<SsbPopoverElement, SsbPopoverEvents, Components.SsbPopover> = /*@__PURE__*/ createComponent<SsbPopoverElement, SsbPopoverEvents, Components.SsbPopover>({
    tagName: 'ssb-popover',
    properties: {
        open: 'open',
        position: 'position',
        align: 'align',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbPopover as StencilReactComponent<SsbPopoverElement, SsbPopoverEvents, Components.SsbPopover>,
    serializeShadowRoot
});
