'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbInputGroup as SsbInputGroupElement, defineCustomElement as defineSsbInputGroup } from "@stencil-storybook-boilerplate/core/dist/components/ssb-input-group.js";

export type SsbInputGroupEvents = NonNullable<unknown>;

export const SsbInputGroup: StencilReactComponent<SsbInputGroupElement, SsbInputGroupEvents, Components.SsbInputGroup> = /*@__PURE__*/ createComponent<SsbInputGroupElement, SsbInputGroupEvents, Components.SsbInputGroup>({
    tagName: 'ssb-input-group',
    elementClass: SsbInputGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbInputGroupEvents,
    defineCustomElement: defineSsbInputGroup
});
