'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbNativeSelectCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbNativeSelect as SsbNativeSelectElement, defineCustomElement as defineSsbNativeSelect } from "@stencil-storybook-boilerplate/core/dist/components/ssb-native-select.js";

export type SsbNativeSelectEvents = { onSsbChange: EventName<SsbNativeSelectCustomEvent<{ value: string }>> };

export const SsbNativeSelect: StencilReactComponent<SsbNativeSelectElement, SsbNativeSelectEvents, Components.SsbNativeSelect> = /*@__PURE__*/ createComponent<SsbNativeSelectElement, SsbNativeSelectEvents, Components.SsbNativeSelect>({
    tagName: 'ssb-native-select',
    elementClass: SsbNativeSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbChange: 'ssbChange' } as SsbNativeSelectEvents,
    defineCustomElement: defineSsbNativeSelect
});
