'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type PaginationPageChangeDetail, type SsbPaginationCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbPagination as SsbPaginationElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-pagination.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbPaginationEvents = { onSsbPageChange: EventName<SsbPaginationCustomEvent<PaginationPageChangeDetail>> };

export const SsbPagination: StencilReactComponent<SsbPaginationElement, SsbPaginationEvents, Components.SsbPagination> = /*@__PURE__*/ createComponent<SsbPaginationElement, SsbPaginationEvents, Components.SsbPagination>({
    tagName: 'ssb-pagination',
    properties: {
        page: 'page',
        totalPages: 'total-pages',
        siblingCount: 'sibling-count',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbPagination as StencilReactComponent<SsbPaginationElement, SsbPaginationEvents, Components.SsbPagination>,
    serializeShadowRoot
});
