'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbToastCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbToast as SsbToastElement, defineCustomElement as defineSsbToast } from "@stencil-storybook-boilerplate/core/dist/components/ssb-toast.js";

export type SsbToastEvents = { onSsbClose: EventName<SsbToastCustomEvent<void>> };

export const SsbToast: StencilReactComponent<SsbToastElement, SsbToastEvents, Components.SsbToast> = /*@__PURE__*/ createComponent<SsbToastElement, SsbToastEvents, Components.SsbToast>({
    tagName: 'ssb-toast',
    elementClass: SsbToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbClose: 'ssbClose' } as SsbToastEvents,
    defineCustomElement: defineSsbToast
});
