'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbNativeSelectCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbNativeSelect as SsbNativeSelectElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-native-select.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbNativeSelectEvents = { onSsbChange: EventName<SsbNativeSelectCustomEvent<{ value: string }>> };

export const SsbNativeSelect: StencilReactComponent<SsbNativeSelectElement, SsbNativeSelectEvents, Components.SsbNativeSelect> = /*@__PURE__*/ createComponent<SsbNativeSelectElement, SsbNativeSelectEvents, Components.SsbNativeSelect>({
    tagName: 'ssb-native-select',
    properties: {
        options: 'options',
        value: 'value',
        name: 'name',
        disabled: 'disabled',
        required: 'required',
        placeholder: 'placeholder',
        size: 'size',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbNativeSelect as StencilReactComponent<SsbNativeSelectElement, SsbNativeSelectEvents, Components.SsbNativeSelect>,
    serializeShadowRoot
});
