'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbChart as SsbChartElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-chart.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbChartEvents = NonNullable<unknown>;

export const SsbChart: StencilReactComponent<SsbChartElement, SsbChartEvents, Components.SsbChart> = /*@__PURE__*/ createComponent<SsbChartElement, SsbChartEvents, Components.SsbChart>({
    tagName: 'ssb-chart',
    properties: {
        type: 'type',
        data: 'data',
        chartHeight: 'chart-height',
        showGrid: 'show-grid',
        showLabels: 'show-labels',
        accent: 'accent',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbChart as StencilReactComponent<SsbChartElement, SsbChartEvents, Components.SsbChart>,
    serializeShadowRoot
});
