'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbTextareaCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTextarea as SsbTextareaElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-textarea.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbTextareaEvents = {
    onSsbInput: EventName<SsbTextareaCustomEvent<{ value: string }>>,
    onSsbChange: EventName<SsbTextareaCustomEvent<{ value: string }>>
};

export const SsbTextarea: StencilReactComponent<SsbTextareaElement, SsbTextareaEvents, Components.SsbTextarea> = /*@__PURE__*/ createComponent<SsbTextareaElement, SsbTextareaEvents, Components.SsbTextarea>({
    tagName: 'ssb-textarea',
    properties: {
        value: 'value',
        placeholder: 'placeholder',
        name: 'name',
        rows: 'rows',
        disabled: 'disabled',
        readonly: 'readonly',
        required: 'required',
        invalid: 'invalid',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbTextarea as StencilReactComponent<SsbTextareaElement, SsbTextareaEvents, Components.SsbTextarea>,
    serializeShadowRoot
});
