'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbComboboxCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCombobox as SsbComboboxElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-combobox.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbComboboxEvents = {
    onSsbChange: EventName<SsbComboboxCustomEvent<{ value: string }>>,
    onSsbOpenChange: EventName<SsbComboboxCustomEvent<{ open: boolean }>>
};

export const SsbCombobox: StencilReactComponent<SsbComboboxElement, SsbComboboxEvents, Components.SsbCombobox> = /*@__PURE__*/ createComponent<SsbComboboxElement, SsbComboboxEvents, Components.SsbCombobox>({
    tagName: 'ssb-combobox',
    properties: {
        options: 'options',
        value: 'value',
        placeholder: 'placeholder',
        searchPlaceholder: 'search-placeholder',
        emptyMessage: 'empty-message',
        disabled: 'disabled',
        open: 'open',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbCombobox as StencilReactComponent<SsbComboboxElement, SsbComboboxEvents, Components.SsbCombobox>,
    serializeShadowRoot
});
