'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbButton as SsbButtonElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-button.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbButtonEvents = NonNullable<unknown>;

export const SsbButton: StencilReactComponent<SsbButtonElement, SsbButtonEvents, Components.SsbButton> = /*@__PURE__*/ createComponent<SsbButtonElement, SsbButtonEvents, Components.SsbButton>({
    tagName: 'ssb-button',
    properties: {
        variant: 'variant',
        size: 'size',
        disabled: 'disabled',
        type: 'type',
        href: 'href',
        target: 'target',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbButton as StencilReactComponent<SsbButtonElement, SsbButtonEvents, Components.SsbButton>,
    serializeShadowRoot
});
