'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSpinner as SsbSpinnerElement, defineCustomElement as defineSsbSpinner } from "@stencil-storybook-boilerplate/core/dist/components/ssb-spinner.js";

export type SsbSpinnerEvents = NonNullable<unknown>;

export const SsbSpinner: StencilReactComponent<SsbSpinnerElement, SsbSpinnerEvents, Components.SsbSpinner> = /*@__PURE__*/ createComponent<SsbSpinnerElement, SsbSpinnerEvents, Components.SsbSpinner>({
    tagName: 'ssb-spinner',
    elementClass: SsbSpinnerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbSpinnerEvents,
    defineCustomElement: defineSsbSpinner
});
