'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbCheckboxCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCheckbox as SsbCheckboxElement, defineCustomElement as defineSsbCheckbox } from "@stencil-storybook-boilerplate/core/dist/components/ssb-checkbox.js";

export type SsbCheckboxEvents = { onSsbChange: EventName<SsbCheckboxCustomEvent<{ checked: boolean }>> };

export const SsbCheckbox: StencilReactComponent<SsbCheckboxElement, SsbCheckboxEvents, Components.SsbCheckbox> = /*@__PURE__*/ createComponent<SsbCheckboxElement, SsbCheckboxEvents, Components.SsbCheckbox>({
    tagName: 'ssb-checkbox',
    elementClass: SsbCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbChange: 'ssbChange' } as SsbCheckboxEvents,
    defineCustomElement: defineSsbCheckbox
});
