'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbSwitchCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSwitch as SsbSwitchElement, defineCustomElement as defineSsbSwitch } from "@stencil-storybook-boilerplate/core/dist/components/ssb-switch.js";

export type SsbSwitchEvents = { onSsbChange: EventName<SsbSwitchCustomEvent<{ checked: boolean }>> };

export const SsbSwitch: StencilReactComponent<SsbSwitchElement, SsbSwitchEvents, Components.SsbSwitch> = /*@__PURE__*/ createComponent<SsbSwitchElement, SsbSwitchEvents, Components.SsbSwitch>({
    tagName: 'ssb-switch',
    elementClass: SsbSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbChange: 'ssbChange' } as SsbSwitchEvents,
    defineCustomElement: defineSsbSwitch
});
