'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbInputCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbInput as SsbInputElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-input.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbInputEvents = {
    onSsbInput: EventName<SsbInputCustomEvent<{ value: string }>>,
    onSsbChange: EventName<SsbInputCustomEvent<{ value: string }>>
};

export const SsbInput: StencilReactComponent<SsbInputElement, SsbInputEvents, Components.SsbInput> = /*@__PURE__*/ createComponent<SsbInputElement, SsbInputEvents, Components.SsbInput>({
    tagName: 'ssb-input',
    properties: {
        type: 'type',
        value: 'value',
        placeholder: 'placeholder',
        name: 'name',
        disabled: 'disabled',
        readonly: 'readonly',
        required: 'required',
        invalid: 'invalid',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbInput as StencilReactComponent<SsbInputElement, SsbInputEvents, Components.SsbInput>,
    serializeShadowRoot
});
