'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTooltip as SsbTooltipElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-tooltip.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbTooltipEvents = NonNullable<unknown>;

export const SsbTooltip: StencilReactComponent<SsbTooltipElement, SsbTooltipEvents, Components.SsbTooltip> = /*@__PURE__*/ createComponent<SsbTooltipElement, SsbTooltipEvents, Components.SsbTooltip>({
    tagName: 'ssb-tooltip',
    properties: {
        text: 'text',
        position: 'position',
        openDelay: 'open-delay',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbTooltip as StencilReactComponent<SsbTooltipElement, SsbTooltipEvents, Components.SsbTooltip>,
    serializeShadowRoot
});
