'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbCommandCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCommand as SsbCommandElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-command.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbCommandEvents = { onSsbSelect: EventName<SsbCommandCustomEvent<{ value: string }>> };

export const SsbCommand: StencilReactComponent<SsbCommandElement, SsbCommandEvents, Components.SsbCommand> = /*@__PURE__*/ createComponent<SsbCommandElement, SsbCommandEvents, Components.SsbCommand>({
    tagName: 'ssb-command',
    properties: {
        items: 'items',
        placeholder: 'placeholder',
        emptyMessage: 'empty-message',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbCommand as StencilReactComponent<SsbCommandElement, SsbCommandEvents, Components.SsbCommand>,
    serializeShadowRoot
});
