'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCard as SsbCardElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-card.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbCardEvents = NonNullable<unknown>;

export const SsbCard: StencilReactComponent<SsbCardElement, SsbCardEvents, Components.SsbCard> = /*@__PURE__*/ createComponent<SsbCardElement, SsbCardEvents, Components.SsbCard>({
    tagName: 'ssb-card',
    properties: { aria: 'aria' },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbCard as StencilReactComponent<SsbCardElement, SsbCardEvents, Components.SsbCard>,
    serializeShadowRoot
});
