'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbTextareaCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTextarea as SsbTextareaElement, defineCustomElement as defineSsbTextarea } from "@stencil-storybook-boilerplate/core/dist/components/ssb-textarea.js";

export type SsbTextareaEvents = {
    onSsbInput: EventName<SsbTextareaCustomEvent<{ value: string }>>,
    onSsbChange: EventName<SsbTextareaCustomEvent<{ value: string }>>
};

export const SsbTextarea: StencilReactComponent<SsbTextareaElement, SsbTextareaEvents, Components.SsbTextarea> = /*@__PURE__*/ createComponent<SsbTextareaElement, SsbTextareaEvents, Components.SsbTextarea>({
    tagName: 'ssb-textarea',
    elementClass: SsbTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbInput: 'ssbInput',
        onSsbChange: 'ssbChange'
    } as SsbTextareaEvents,
    defineCustomElement: defineSsbTextarea
});
