'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbLabel as SsbLabelElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-label.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbLabelEvents = NonNullable<unknown>;

export const SsbLabel: StencilReactComponent<SsbLabelElement, SsbLabelEvents, Components.SsbLabel> = /*@__PURE__*/ createComponent<SsbLabelElement, SsbLabelEvents, Components.SsbLabel>({
    tagName: 'ssb-label',
    properties: {
        htmlFor: 'html-for',
        required: 'required',
        disabled: 'disabled',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbLabel as StencilReactComponent<SsbLabelElement, SsbLabelEvents, Components.SsbLabel>,
    serializeShadowRoot
});
