'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbCommandCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbCommand as SsbCommandElement, defineCustomElement as defineSsbCommand } from "@stencil-storybook-boilerplate/core/dist/components/ssb-command.js";

export type SsbCommandEvents = { onSsbSelect: EventName<SsbCommandCustomEvent<{ value: string }>> };

export const SsbCommand: StencilReactComponent<SsbCommandElement, SsbCommandEvents, Components.SsbCommand> = /*@__PURE__*/ createComponent<SsbCommandElement, SsbCommandEvents, Components.SsbCommand>({
    tagName: 'ssb-command',
    elementClass: SsbCommandElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbSelect: 'ssbSelect' } as SsbCommandEvents,
    defineCustomElement: defineSsbCommand
});
