'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbRadioCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbRadio as SsbRadioElement, defineCustomElement as defineSsbRadio } from "@stencil-storybook-boilerplate/core/dist/components/ssb-radio.js";

export type SsbRadioEvents = { onSsbRadioSelect: EventName<SsbRadioCustomEvent<{ value: string }>> };

export const SsbRadio: StencilReactComponent<SsbRadioElement, SsbRadioEvents, Components.SsbRadio, 'value'> = /*@__PURE__*/ createComponent<SsbRadioElement, SsbRadioEvents, Components.SsbRadio, 'value'>({
    tagName: 'ssb-radio',
    elementClass: SsbRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbRadioSelect: 'ssbRadioSelect' } as SsbRadioEvents,
    defineCustomElement: defineSsbRadio
});
