'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbDrawerCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbDrawer as SsbDrawerElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-drawer.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbDrawerEvents = { onSsbOpenChange: EventName<SsbDrawerCustomEvent<{ open: boolean }>> };

export const SsbDrawer: StencilReactComponent<SsbDrawerElement, SsbDrawerEvents, Components.SsbDrawer> = /*@__PURE__*/ createComponent<SsbDrawerElement, SsbDrawerEvents, Components.SsbDrawer>({
    tagName: 'ssb-drawer',
    properties: {
        open: 'open',
        side: 'side',
        drawerTitle: 'drawer-title',
        description: 'description',
        hideClose: 'hide-close',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbDrawer as StencilReactComponent<SsbDrawerElement, SsbDrawerEvents, Components.SsbDrawer>,
    serializeShadowRoot
});
