'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbEmpty as SsbEmptyElement, defineCustomElement as defineSsbEmpty } from "@stencil-storybook-boilerplate/core/dist/components/ssb-empty.js";

export type SsbEmptyEvents = NonNullable<unknown>;

export const SsbEmpty: StencilReactComponent<SsbEmptyElement, SsbEmptyEvents, Components.SsbEmpty> = /*@__PURE__*/ createComponent<SsbEmptyElement, SsbEmptyEvents, Components.SsbEmpty>({
    tagName: 'ssb-empty',
    elementClass: SsbEmptyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbEmptyEvents,
    defineCustomElement: defineSsbEmpty
});
