'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAvatar as SsbAvatarElement, defineCustomElement as defineSsbAvatar } from "@stencil-storybook-boilerplate/core/dist/components/ssb-avatar.js";

export type SsbAvatarEvents = NonNullable<unknown>;

export const SsbAvatar: StencilReactComponent<SsbAvatarElement, SsbAvatarEvents, Components.SsbAvatar> = /*@__PURE__*/ createComponent<SsbAvatarElement, SsbAvatarEvents, Components.SsbAvatar>({
    tagName: 'ssb-avatar',
    elementClass: SsbAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbAvatarEvents,
    defineCustomElement: defineSsbAvatar
});
