'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbDropdownMenuCustomEvent } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbDropdownMenu as SsbDropdownMenuElement, defineCustomElement as defineSsbDropdownMenu } from "@stencil-storybook-boilerplate/core/dist/components/ssb-dropdown-menu.js";

export type SsbDropdownMenuEvents = {
    onSsbSelect: EventName<SsbDropdownMenuCustomEvent<{ value: string }>>,
    onSsbOpenChange: EventName<SsbDropdownMenuCustomEvent<{ open: boolean }>>
};

export const SsbDropdownMenu: StencilReactComponent<SsbDropdownMenuElement, SsbDropdownMenuEvents, Components.SsbDropdownMenu> = /*@__PURE__*/ createComponent<SsbDropdownMenuElement, SsbDropdownMenuEvents, Components.SsbDropdownMenu>({
    tagName: 'ssb-dropdown-menu',
    elementClass: SsbDropdownMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSsbSelect: 'ssbSelect',
        onSsbOpenChange: 'ssbOpenChange'
    } as SsbDropdownMenuEvents,
    defineCustomElement: defineSsbDropdownMenu
});
