'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbProgress as SsbProgressElement, defineCustomElement as defineSsbProgress } from "@stencil-storybook-boilerplate/core/dist/components/ssb-progress.js";

export type SsbProgressEvents = NonNullable<unknown>;

export const SsbProgress: StencilReactComponent<SsbProgressElement, SsbProgressEvents, Components.SsbProgress> = /*@__PURE__*/ createComponent<SsbProgressElement, SsbProgressEvents, Components.SsbProgress>({
    tagName: 'ssb-progress',
    elementClass: SsbProgressElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbProgressEvents,
    defineCustomElement: defineSsbProgress
});
