'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbLabel as SsbLabelElement, defineCustomElement as defineSsbLabel } from "@stencil-storybook-boilerplate/core/dist/components/ssb-label.js";

export type SsbLabelEvents = NonNullable<unknown>;

export const SsbLabel: StencilReactComponent<SsbLabelElement, SsbLabelEvents, Components.SsbLabel> = /*@__PURE__*/ createComponent<SsbLabelElement, SsbLabelEvents, Components.SsbLabel>({
    tagName: 'ssb-label',
    elementClass: SsbLabelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbLabelEvents,
    defineCustomElement: defineSsbLabel
});
