'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbAlert as SsbAlertElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-alert.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbAlertEvents = NonNullable<unknown>;

export const SsbAlert: StencilReactComponent<SsbAlertElement, SsbAlertEvents, Components.SsbAlert> = /*@__PURE__*/ createComponent<SsbAlertElement, SsbAlertEvents, Components.SsbAlert>({
    tagName: 'ssb-alert',
    properties: {
        variant: 'variant',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbAlert as StencilReactComponent<SsbAlertElement, SsbAlertEvents, Components.SsbAlert>,
    serializeShadowRoot
});
