'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTable as SsbTableElement, defineCustomElement as defineSsbTable } from "@stencil-storybook-boilerplate/core/dist/components/ssb-table.js";

export type SsbTableEvents = NonNullable<unknown>;

export const SsbTable: StencilReactComponent<SsbTableElement, SsbTableEvents, Components.SsbTable> = /*@__PURE__*/ createComponent<SsbTableElement, SsbTableEvents, Components.SsbTable>({
    tagName: 'ssb-table',
    elementClass: SsbTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SsbTableEvents,
    defineCustomElement: defineSsbTable
});
