'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type SsbSliderCustomEvent } from "@stencil-storybook-boilerplate/core";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbSlider as SsbSliderElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-slider.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbSliderEvents = {
    onSsbInput: EventName<SsbSliderCustomEvent<{ value: number }>>,
    onSsbChange: EventName<SsbSliderCustomEvent<{ value: number }>>
};

export const SsbSlider: StencilReactComponent<SsbSliderElement, SsbSliderEvents, Components.SsbSlider> = /*@__PURE__*/ createComponent<SsbSliderElement, SsbSliderEvents, Components.SsbSlider>({
    tagName: 'ssb-slider',
    properties: {
        value: 'value',
        min: 'min',
        max: 'max',
        step: 'step',
        disabled: 'disabled',
        showValue: 'show-value',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbSlider as StencilReactComponent<SsbSliderElement, SsbSliderEvents, Components.SsbSlider>,
    serializeShadowRoot
});
