'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SsbTabsCustomEvent, type TabsChangeDetail } from "@stencil-storybook-boilerplate/core";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbTabs as SsbTabsElement, defineCustomElement as defineSsbTabs } from "@stencil-storybook-boilerplate/core/dist/components/ssb-tabs.js";

export type SsbTabsEvents = { onSsbChange: EventName<SsbTabsCustomEvent<TabsChangeDetail>> };

export const SsbTabs: StencilReactComponent<SsbTabsElement, SsbTabsEvents, Components.SsbTabs> = /*@__PURE__*/ createComponent<SsbTabsElement, SsbTabsEvents, Components.SsbTabs>({
    tagName: 'ssb-tabs',
    elementClass: SsbTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSsbChange: 'ssbChange' } as SsbTabsEvents,
    defineCustomElement: defineSsbTabs
});
