'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@stencil-storybook-boilerplate/core/client";
import type { Components } from "@stencil-storybook-boilerplate/core/dist/components";
import { SsbBreadcrumb as SsbBreadcrumbElement } from "@stencil-storybook-boilerplate/core/dist/components/ssb-breadcrumb.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type SsbBreadcrumbEvents = NonNullable<unknown>;

export const SsbBreadcrumb: StencilReactComponent<SsbBreadcrumbElement, SsbBreadcrumbEvents, Components.SsbBreadcrumb> = /*@__PURE__*/ createComponent<SsbBreadcrumbElement, SsbBreadcrumbEvents, Components.SsbBreadcrumb>({
    tagName: 'ssb-breadcrumb',
    properties: {
        items: 'items',
        separator: 'separator',
        aria: 'aria'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@stencil-storybook-boilerplate/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.SsbBreadcrumb as StencilReactComponent<SsbBreadcrumbElement, SsbBreadcrumbEvents, Components.SsbBreadcrumb>,
    serializeShadowRoot
});
