
import * as d from './components';

export const DIRECTIVES = [
  d.MyComponent,
  d.SsbAccordion,
  d.SsbAccordionItem,
  d.SsbAlert,
  d.SsbAlertDialog,
  d.SsbAvatar,
  d.SsbBadge,
  d.SsbBreadcrumb,
  d.SsbButton,
  d.SsbButtonGroup,
  d.SsbCard,
  d.SsbCheckbox,
  d.SsbDialog,
  d.SsbDropdownMenu,
  d.SsbEmpty,
  d.SsbField,
  d.SsbInput,
  d.SsbInputGroup,
  d.SsbItem,
  d.SsbKbd,
  d.SsbLabel,
  d.SsbNativeSelect,
  d.SsbPagination,
  d.SsbPopover,
  d.SsbProgress,
  d.SsbRadio,
  d.SsbRadioGroup,
  d.SsbScrollArea,
  d.SsbSkeleton,
  d.SsbSlider,
  d.SsbSpinner,
  d.SsbSwitch,
  d.SsbTable,
  d.SsbTabs,
  d.SsbTextarea,
  d.SsbThemeSwitcher,
  d.SsbToast,
  d.SsbTooltip
];
